name: precifica
description: "Um aplicativo que ajuda na precificação de produtos."
publish_to: 'none'
version: 1.5.2+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flutter_riverpod: ^3.0.0-dev.3
  uuid: ^4.4.0
  share_plus: ^9.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  path: ^1.9.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1

  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/profiles/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon_foreground.png"